### ISSUE TITLE
Broken markup

### ISSUE THREAD

**Issue by hirasso** [GODLiangCY/markdown-it-shiki-extra#1]
Hi there! 

Congrats to this package. The diffing support is amazing! There were two issues in `markdown-it-shiki` that were fixed after you had already forked it. Would you care to port them over to `markdown-it-shiki-extra`? Both are related to outputting valid and predictable markup:

**Discussion**: https://github.com/antfu/markdown-it-shiki/issues/17

**Merged PRs:**
- https://github.com/antfu/markdown-it-shiki/pull/16
- https://github.com/antfu/markdown-it-shiki/pull/18

**Comment by younggglcy** [comment]
Thank you!
